name: CI

on:
  push:
    branches: [ '[1-9].[0-9]+' ]
  pull_request:
    branches: [ '[1-9].[0-9]+' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2', '8.3', '8.4']
    name: PHP ${{ matrix.php-versions }}

    steps:
    - uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: json
        coverage: none # disable xdebug
        ini-values: date.timezone=Europe/Paris
    - name: Check PHP Version
      run: php -v

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: vendor/bin/phpunit

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: json
          ini-values: date.timezone=Europe/Paris

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test coverage
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
